### ISSUE TITLE
Found test problem caused by changes of working directory in backend

### ISSUE THREAD

**Issue by dafrose** [pyrates-neuroscience/PyRates#18]
While trying to understand differences between tests run on Windows and Linux I found that some problems (at least) are cause by the backend changing directories. @Richert : Can we change that?

**Comment by dafrose** [comment]
fixed this by introducing a pytest fixture that changes the working directory after a test to what it was before. 494b3e8c9ce7bcdf70360bb88f6f8b551f1c7b73

**Comment by dafrose** [comment]
After further investigation I found that two backend tests where still affected by the change of directory: tests `test_1_5_...` and `test_1_6_...` create and change directories many times in a row, leading to somewhat recursive creation of sub-directories, because the numpy backend does not switch back to the original directory after one run. This leads to an error on Windows, because the maximum allowed length of a path is hit (as not indicated by the error message `FileNotFoundError`). I added the line `os.chdir(orig_dir)` at the end of the `__init__` method of the numpy backend to prevent this. Now all tests are working both on Linux and Windows. Is this solution acceptable? Can the numpy backend also run without changing directories at all?

**Comment by Richert** [comment]
This solution is acceptable. The `NumpyBackend.compile` method changes the directory itself during the build process and always used `os.chdir(orig_dir)` as a last step. Since I never used the frontend in isolation, I apparently forgot to account for the case that the `__init__` of the `NumpyBackend` is called, but not the `compile` method. Which I suppose causes the problems on Windows.

Theoretically, we could also change the numpy backend to not change directories at all. However, this would require to create build paths with init files along the way, such that they are recognized as proper python modules. In other words, more temporary files would be created.

**Comment by dafrose** [comment]
Ok, closing now. Diagnosis shows that some tests still exit with a changed working directory, but the pytest fixture in `conftest.py` reverts to the original one. Btw., I also added a fixture that makes sure, tests are run in the tests/ folder and not in the parent folder (which travis CI does by default and which caused other problems.)
