### ISSUE TITLE
Removing parts of pyrates from sys.modules in the backend causes troubles in other parts of the pipeline

### ISSUE THREAD

**Issue by dafrose** [pyrates-neuroscience/PyRates#19]
While debugging strange errors, I discovered that in lines 949-951 of pyrates.backend.numpy_backend the current collection known python modules is modified (`sys.modules`). In fact, all modules that contain the name of the current object instance (in this case "circuit") are removed. This state is kept across tests and thus leads to problems in other tests. However, I expect this to cause problems in productive code as well, because this is unexpected behaviour.

Commenting these lines out removed the problem and all (!) tests completed successfully. Is there a reason to keep these lines? @Richert

**Comment by Richert** [comment]
This code was introduced at some point in order to prevent exactly those problems "in other tests". When running different tests with different circuit structures that, however, included the exact same module names, `sys.modules` would not update the modules between tests. Thus, this code was added to ensure that modules from older versions of the same circuit would be forgotten, so that the new ones could be added to  `sys.modules`.  Since every `CircuitIR` instance comes with just one backend, I did not expect this to cause trouble in "productive code". Also, I never ran into strange bugs. However, it is possible that changes to the code generation structure further down the line made this code unnecessary. Thus, I will see whether removing it causes any other problems. If not, we can get rid of it.

**Comment by dafrose** [comment]
Okay, so the problem is that Python registers modules for the backend that may need to be refreshed, correct? In may case, the backend removed all modules that contained "circuit" in their, thus also removing PyRates' own modules for circuit templates and IR. That again cause a problem somewhere else, when I wanted to verify instances of template classes. Checking for instance itself is not a good practice in Python, so it might also be worth rewriting those checks... 

Either, I'll still leave this open until we have decided, whether the current fix is acceptable or not.

**Comment by Richert** [comment]
So I removed these parts of the code and they did not change anything about running the pytests or other test scripts on my end. I pushed the changes and will close this issue now.
