### ISSUE TITLE
Add possibility to CircuitTemplate.apply() method to change constants

### ISSUE THREAD

**Issue by Richert** [pyrates-neuroscience/PyRates#22]
This is a suggestion on how to improve the flexibility of working with YAML templates for model definitions in PyRates.

I suggest to add an additional keyword argument to the `pyrates.frontend.CircuitTemplate.apply()` method. This keyword argument should be a dictionary, which allows to point to any variable on any operator on any node or edge in the graph via the standard slash-based notation and change its scalar value.

This would enable quick parameter changes within Python without the necessity of defining new yaml templates. Thus, interacting with the pre-implemented models in `model_definitions` becomes more intuitive, since users would not have to mess with the yaml templates in order to apply a simple parameter change. Finally, it would allow to change initial values of state variables more easily.

**Comment by dafrose** [comment]
Funny... I kind of expected to work already, but it doesn't. All other templates already support that functionality. Thus, it is only a matter having the keyword/dictionary point to the respective node/edge and so on. For nodes it should be easy. For edges it is necessary to specify source and target as in the template and it might still not be unique, if multiple edges between the same nodes are defined in a circuit template. I do not think, there is an easy way around this (except for overwriting the edges in a custom yaml/Python template).

Thus the partial solution: Implement `node_values` keyword argument, that can point to nodes by key as defined in the template. The rest is simply passed to the node template's `apply` method. I would prefer to leave edges the way they are now, because this could potentially introduce bugs leading to unexpected results (or confuse error handling). Would that be sufficient for now?

**Comment by Richert** [comment]
I think that sounds like a good temporary solution. If we have a good idea for how to handle changes to edge attributes during the `CircuitTemplate.apply()` call, we can easily add this later on.

**Comment by dafrose** [comment]
Implemented with 1d4428ee8bfe79f6b3c006c372eb34e94ea16bbe . Behaviour is documented in test_frontend_yaml_parser.py/test_circuit_instantiation. I went for a dictionary of the form `{'node/op/var':value}` for consistency with existing APIs. Closing.
