### ISSUE TITLE
issues when running the example codes

### ISSUE THREAD

**Issue by GanshengT** [pyrates-neuroscience/PyRates#30]
Hi, I was trying to run the codes from the documentation example:

from pyrates.frontend import CircuitTemplate
jrc = CircuitTemplate.from_yaml("model_templates.neural_mass_models.jansenrit.JRC")
results = jrc.run(simulation_time=1.0,
                  step_size=1e-2,
                  sampling_step_size=1e-2,
                  outputs={'V_pce': 'pc/rpo_e_in/Z',
                           'V_pci': 'pc/rpo_i/Z'},
                  backend='default',
                  solver='scipy')

It yields value error.

I run in Jupiter notebook with python 3.8 kernel. The spicy version is 1.7.3. The detail errors are shown below:

ValueError                                Traceback (most recent call last)

      1 from pyrates.frontend import CircuitTemplate
      2 jrc = CircuitTemplate.from_yaml("model_templates.neural_mass_models.jansenrit.JRC")
----> 3 results = jrc.run(simulation_time=1.0,
      4                   step_size=1e-2,
      5                   sampling_step_size=1e-2,

in pyrates/frontend/template/circuit.py in run(self, simulation_time, step_size, inputs, outputs, sampling_step_size, cutoff, solver, backend, vectorize, verbose, clear, in_place, **kwargs)
    322 
    323         # apply template (translate into compute graph, optional vectorization process)
--> 324         net.apply(adaptive_steps=adaptive_steps, vectorize=vectorize, verbose=verbose, backend=backend,
    325                   step_size=step_size, **kwargs)
    326 

in pyrates/frontend/template/circuit.py in apply(self, adaptive_steps, label, node_values, edge_values, vectorize, verbose, **kwargs)
    517 
    518         # group edges that should be vectorized
--> 519         old_edges = self.collect_edges(delay_info=True)
    520         edge_col = self._group_edges(edges=old_edges)
    521 

in pyrates/frontend/template/circuit.py in collect_edges(self, delay_info)
    799                 edges.append((f"{c_scope}/{svar}", f"{c_scope}/{tvar}", template, edge_dict))
    800         if delay_info:
--> 801             for i, (svar, tvar, template, edge) in enumerate(edges):
    802                 delayed = True if 'delay' in edge and edge['delay'] else False
    803                 edges[i] = (svar, tvar, template, edge, delayed)

ValueError: too many values to unpack (expected 4)

Perhaps no edge is generated? What are your thoughts?

**Comment by Richert** [comment]
Hi @GanshengT ,

Thank you for your interest in working with PyRates.
From your example, I think the issue is connected to multiple executions of your jupyter notebook cells.
When calling `CircuitTemplate.run`, PyRates uses a caching system to reduce the number of templates that have to be loaded separately. These templates, however, are altered along the process of translating a given model into the backend. Thus, the cache has to be cleared first, before you can call `CircuitTemplate.run` again. 

I think the following adjustments just allow to execute a cell with your code multiple times:

```
from pyrates import CircuitTemplate, clear_frontend_caches

jrc = CircuitTemplate.from_yaml("model_templates.neural_mass_models.jansenrit.JRC")
results = jrc.run(simulation_time=1.0,
                          step_size=1e-2,
                          sampling_step_size=1e-2,
                          outputs={'V_pce': 'pc/rpo_e_in/V',
                          'V_pci': 'pc/rpo_i/V'},
                          backend='default',
                          solver='scipy')
``` 

Notice, that I have also changed the name of the output variables from `Z` to `V`, to account for a recent modification I made to the model templates. Should you not use the most recent version of PyRates, feel free to go back to your original variable names. For me, the code above worked with the most recent PyRates version, using Python 3.8 and jupyter notebook on Ubuntu 20.04.

Hope that solves your problem!

**Comment by GanshengT** [comment]
Thank you for the prompt response! It did solve the problem!
